# ==========================================================
# [?? ?? ??]
# ==========================================================
server:
  port: 8080 # ?????? ?? ?? (?? 8080)
  servlet:
    encoding:
      charset: UTF-8
      force: true

# ==========================================================
# [Spring ??]
# ==========================================================
spring:
  profiles:
    active: local
